version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/e1-2022-1-grupo_13
hooks:
  BeforeInstall:
    - location: scripts/before-install.sh
      runas: ubuntu
      timeout: 300
  AfterInstall:
    - location: scripts/after-install.sh
      runas: ubuntu
      timeout: 300