version: 0.0
os: linux
files:
  - source: .
    destination: /home/ec2-user/e1-2022-1-grupo_13
hooks:
  AfterInstall:
   - location: setup.sh
     timeout: 300
     runas: root
  ApplicationStart:
   - location: run.sh
     timeout: 300
     runas: root     
