version: '3'
services:
  db:
    image: postgres:13
    volumes:
      - messagingDB:/var/lib/postgresql/data
    env_file: 
      - ./.env_db
    ports:
      - "5400:5400"
  chat:
    build:
      context: chat
      dockerfile: Dockerfile
    container_name: chat
    restart: always
    volumes:
      - /usr/src/chat/node_modules
      - ./chat/:/usr/src/chat
    ports:
      - "7777:7777"
      - "9229:9229"
    command:
      "npm run debug"
    env_file: 
      - ./.env
    environment:
      - DUMMY=0
    depends_on:
      - db
      - pubsub
  pubsub:
    image: redis:latest
    ports:
      - "6379:6379"
volumes:
  messagingDB: