# Generated by Django 3.2.9 on 2022-06-27 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index_sidi', models.DecimalField(decimal_places=10, max_digits=19)),
                ('index_siin', models.DecimalField(decimal_places=10, max_digits=19)),
                ('index_dindin', models.DecimalField(decimal_places=10, max_digits=19)),
            ],
        ),
    ]
